"""Agrega columna hora_salida a la tabla ruta

Revision ID: 46cd89a7a6c1
Revises: 
Create Date: 2025-05-20 15:47:23.168493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46cd89a7a6c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disponibilidad')
    with op.batch_alter_table('ruta', schema=None) as batch_op:
        batch_op.drop_column('distancia_km')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ruta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distancia_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))

    op.create_table('disponibilidad',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('viaje_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('asientos_totales', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('asientos_disponibles', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['viaje_id'], ['viaje.id'], name='disponibilidad_viaje_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='disponibilidad_pkey')
    )
    # ### end Alembic commands ###
