"""Añadir hora_salida/hora_llegada a ruta

Revision ID: fd85cd39cca5
Revises: 3e5cdfcb4a28
Create Date: 2025-05-20 23:14:44.342293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fd85cd39cca5'
down_revision = '3e5cdfcb4a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ruta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hora_salida', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('hora_llegada', sa.String(length=100), nullable=False))
        batch_op.drop_column('tiempo_estimado')

    with op.batch_alter_table('viaje', schema=None) as batch_op:
        batch_op.drop_column('fecha_llegada')
        batch_op.drop_column('fecha_salida')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viaje', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_salida', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('fecha_llegada', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))

    with op.batch_alter_table('ruta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tiempo_estimado', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('hora_llegada')
        batch_op.drop_column('hora_salida')

    # ### end Alembic commands ###
