services:
  postgresql:
    image: postgres:16.4-alpine
    container_name: recorrido-postgresql
    networks:
      - mired    
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: recorrido-pgadmin
    networks:
      - mired  
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}   
    ports: 
      - "8080:80"
    depends_on: 
      - postgresql

networks:
  mired:
    external: true
