import json

# Datos extraídos de la imagen del recorrido del colectivo 511
recorrido_511 = {
    "linea": "511 Urbano",
    "trayecto": "Río Diamante / Cuadro Nacional por Sarmiento",
    "frecuencia_minutos": 30,
    "inicio_servicio": "06:00",
    "ida": [
        "Ruta Nac. N 143",
        "T. Angrimán",
        "Papa J. XXIII",
        "Dr. F. Alcorta",
        "Cangallo",
        "Florida",
        "Los Sauces",
        "C. Silva",
        "C.J. Benelli",
        "Fray Inalicán",
        "Jujuy",
        "Av. Quiroga",
        "Cabildo",
        "Sarmiento",
        "J. Bosco",
        "Perú",
        "Libertad",
        "Montecaseros",
        "Santa Fe",
        "Entre Ríos",
        "Corrientes",
        "Cnel. Suárez",
        "Misiones",
        "Formosa",
        "Rep. de Israel",
        "Chaco",
        "La Pampa",
        "Río Negro",
        "Chubut",
        "Neuquén",
        "Santa Cruz",
        "La Rioja",
        "Catamarca",
        "Tucumán",
        "I. Sueta",
        "El Fortín",
        "Callejón Palacios",
        "San Francisco",
        "San Pedro",
        "Av. Mitre",
        "E. Salas",
        "Ruta Nac. 146",
        "Los Ranqueles"
    ],
    "vuelta": [
        "Los Ranqueles",
        "Ruta Nac. 146",
        "E. Salas",
        "Av. Mitre",
        "San Pedro",
        "San Francisco",
        "Callejón Palacios",
        "El Fortín",
        "I. Sueta",
        "Tucumán",
        "Catamarca",
        "La Rioja",
        "Sta. Cruz",
        "Neuquén",
        "Chubut",
        "Río Negro",
        "La Pampa",
        "Chaco",
        "Rep. de Israel",
        "Formosa",
        "Misiones",
        "Bolívar",
        "América",
        "Tacuari",
        "Reconquista",
        "Balcarce",
        "Pichincha",
        "Pringles",
        "Sgto. Cabral",
        "Isaac Esponda",
        "Segovia",
        "Av. Colón",
        "Cte. Torres",
        "E. Civit",
        "Las Heras",
        "San Lorenzo",
        "Av. El Libertador",
        "Avellaneda",
        "Almafuerte",
        "Godoy Cruz",
        "Gutiérrez",
        "25 de Mayo",
        "Av. 9 de Julio",
        "3 de Febrero",
        "Lugones",
        "Los Franceses",
        "Av. Balloffet",
        "G. Roca",
        "Los Sauces",
        "J. Braña",
        "Capdeville",
        "Sgo. Derqui",
        "Dr. J. Celman",
        "Sgto. Grain",
        "Dr. Quintana",
        "J. Páez",
        "Los Filtros",
        "R. Peña",
        "Amapola",
        "V. de la Plaza",
        "Salida: Eucaliptus y Sarmiento"
    ]
}

# Guardar en archivo JSON
with open("recorrido_511.json", "w", encoding="utf-8") as f:
    json.dump(recorrido_511, f, ensure_ascii=False, indent=4)

print("Archivo JSON generado correctamente: recorrido_511.json")
